CREATE TABLE company
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    logo         VARCHAR(255),
    industry     VARCHAR(255),
    headquarters VARCHAR(255),
    size         INTEGER,
    website      VARCHAR(255),
    CONSTRAINT pk_company PRIMARY KEY (id)
);

CREATE TABLE employee
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_id          BIGINT                                  NOT NULL,
    job_level_id        BIGINT                                  NOT NULL,
    position            VARCHAR(255),
    location            VARCHAR(255),
    years_of_experience INTEGER,
    years_at_company    INTEGER,
    CONSTRAINT pk_employee PRIMARY KEY (id)
);

CREATE TABLE job_level
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_id       BIGINT                                  NOT NULL,
    title            VARCHAR(255),
    level_number     INTEGER,
    equivalent_level VARCHAR(255),
    CONSTRAINT pk_job_level PRIMARY KEY (id)
);

CREATE TABLE review
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id BIGINT                                  NOT NULL,
    rating      INTEGER,
    review_text VARCHAR(255),
    date        date,
    CONSTRAINT pk_review PRIMARY KEY (id)
);

CREATE TABLE salary
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id        BIGINT                                  NOT NULL,
    base_salary        DOUBLE PRECISION,
    stock_options      DOUBLE PRECISION,
    bonus              DOUBLE PRECISION,
    total_compensation DOUBLE PRECISION,
    currency           VARCHAR(255),
    CONSTRAINT pk_salary PRIMARY KEY (id)
);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_JOB_LEVEL FOREIGN KEY (job_level_id) REFERENCES job_level (id);

ALTER TABLE job_level
    ADD CONSTRAINT FK_JOB_LEVEL_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);

ALTER TABLE salary
    ADD CONSTRAINT FK_SALARY_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);